name: cnc-conf-gpcs-remote
label: CNC Config for GPCS Remote CPE
description: GPCS Remote CPE Configuration
type: template
extends:

labels:
  customize_field: snippet_name
  customize_label_name: service_type
  customize_label_value: gpcs-cpe

variables:
  - name: customer_name
    description: Customer Name
    default: ACME
    type_hint: dropdown
    dd_list:
      - key: PAN-A7-40646123 - Cara S. Mcintosh
        value: Mcintosh
      - key: PAN-A8-89390058 - Carter Hawkins
        value: Hawkins
      - key: PAN-A7-34061387 - Ella V. Durham
        value: Durham
      - key: PAN-A9-42896926 - Jaden Hubbard
        value: Hubbard
      - key: PAN-A8-08492225 - Cadman D. Blanchard
        value: Blanchard
      - key: PAN-A8-99098632 - Ebony B. Bray
        value: Bray
      - key: PAN-B8-62338140 - Kiayada Petty
        value: Petty
  - name: snippet_name
    description: CPE Vendor
    default: junos
    type_hint: text


snippets:

