name: mssp

repositories:
  - name: Iron-Skillet-v81
    url: https://github.com/PaloAltoNetworks/iron-skillet.git
    branch: 81dev
    destination_directory: skillet81
    repositories:
  - name: MSSP Templates
    url:  https://github.com/scotchoaf/mssp-templates.git
    branch: 81dev
    destination_directory: gsb81

views:

  - name: ''
    class: CNCView
    menu: MSSP Security Offerings
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Skillet
      description: MSSP GSB Configurations
      documentation_link: http://iron-skillet_panorama_dg.readthedocs.io

  - name: gsbconfig
    class: ChooseSnippetView
    menu: MSSP Security Offerings
    menu_option: Basic Internet Gateway
    attributes:
      snippet: cnc-conf-gsb-panorama
      header: Initial Service Request
      title: Select Configuration Options
      next_url: gsbworkflow01

  - name: gsbconfigpanos
    class: ChooseSnippetView
    menu: MSSP Security Offerings
    menu_option: Basic Internet Gateway for PAN-OS
    attributes:
      snippet: cnc-conf-gsb-panos
      header: Initial Service Request
      title: Select Configuration Option
      next_url: gsbworkflow01

  - name: gsbworkflow01
    class: gsbProvisionView
    attributes:
      next_url: provision

  - name: gsbsetconfig
    class: ChooseSnippetByLabelView
    menu: MSSP Security Offerings
    menu_option: GSB SET commands
    attributes:
      label_name: service_type
      label_value: internet_gateway_set
      header: Choose set command file
      title: Select Configuration Option

  - name: gpcsconfig
    class: ChooseSnippetView
    menu: MSSP Security Offerings
    menu_option: Global Protect Cloud Service
    attributes:
      snippet: cnc-conf-gpcs
      header: Initial Service Request
      title: Select Configuration Option

  - name: gpcscpeconfig
    class: ChooseSnippetByLabelView
    menu: MSSP Security Offerings
    menu_option: GPCS CPE Helper Configs
    attributes:
      label_name: service_type
      label_value: gpcs-cpe
      header: Select CPE Type
      title: Select Configuration Option

  - name: provision
    class: ProvisionSnippetView




