name: mssp

views:

  - name: ''
    class: CNCView
    menu: MSSP Security Offerings
    menu_option: Welcome
    attributes:
      template_name: pan_cnc/welcome.html
    context:
      title: Skillet
      description: MSSP GSB Configurations
      documentation_link: http://iron-skillet_panorama_dg.readthedocs.io

  - name: gsbconfig
    class: ChooseSnippetView
    menu: MSSP Security Offerings
    menu_option: Basic Internet Gateway
    attributes:
      snippet: cnc-conf-gsb
      header: Initial Service Request
      title: Select Configuration Option

  - name: gpcsconfig
    class: ChooseSnippetView
    menu: MSSP Security Offerings
    menu_option: Global Protect Cloud Service
    attributes:
      snippet: cnc-conf-gpcs
      header: Initial Service Request
      title: Select Configuration Option

  - name: gpcscpeconfig
    class: ChooseSnippetByLabelView
    menu: MSSP Security Offerings
    menu_option: GPCS CPE Helper Configs
    attributes:
      label_name: service_type
      label_value: gpcs-cpe
      header: Select CPE Type
      title: Select Configuration Option

  - name: provision
    class: ProvisionSnippetView




